@echo off
setlocal enabledelayedexpansion

cd /d "%~dp0"

if not exist .env (
    echo ERROR: .env file not found!
    echo Run setup.bat first to initialize the application.
    pause
    exit /b 1
)

if not exist docker-compose.yml (
    echo ERROR: docker-compose.yml not found!
    echo Download it from the EcoGallery releases page.
    pause
    exit /b 1
)

REM Validate API_KEY is set (should have been generated by setup.bat)
for /f "tokens=2 delims==" %%i in ('findstr /B "API_KEY=" .env') do set "EXISTING_API_KEY=%%i"
if "!EXISTING_API_KEY!"=="CHANGE_ME_TO_A_SECURE_RANDOM_STRING" (
    echo ERROR: API_KEY is still using the placeholder value!
    echo Run setup.bat first to initialize the application.
    pause
    exit /b 1
)
if "!EXISTING_API_KEY!"=="" (
    echo ERROR: API_KEY is not set in .env!
    echo Run setup.bat first to initialize the application.
    pause
    exit /b 1
)

REM Load .env for display
for /f "usebackq tokens=1,* delims==" %%a in (".env") do (
    set "line=%%a"
    if not "!line:~0,1!"=="#" if not "!line!"=="" (
        set "%%a=%%b"
    )
)

REM Start the application in detached mode
docker compose up -d --pull always

REM Show status
docker compose ps
echo ======================================
echo   EcoGallery is running!
echo ======================================

if "%HTTP_PORT%"=="" (
    echo Access the application at: http://localhost
) else if "%HTTP_PORT%"=="80" (
    echo Access the application at: http://localhost
) else (
    echo Access the application at: http://localhost:%HTTP_PORT%
)
echo Useful commands:
echo   docker compose logs -f          # View logs
echo   docker compose down             # Stop ecogallery
echo   docker compose ps               # Check status
echo ======================================
pause