#!/bin/bash
set -e

echo "======================================"
echo "  EcoGallery - Start Application"
echo "======================================"
echo ""

cd "$(dirname "$0")"

if [ ! -f .env ]; then
    echo "ERROR: .env file not found!"
    echo "Run ./setup.sh first to initialize the application."
    exit 1
fi

if [ ! -f docker-compose.yml ]; then
    echo "ERROR: docker-compose.yml not found!"
    echo "Download it from the EcoGallery releases page."
    exit 1
fi

# Validate API_KEY is set (should have been generated by setup.sh)
EXISTING_API_KEY=$(grep '^API_KEY=' .env 2>/dev/null | cut -d'=' -f2)
if [ "${EXISTING_API_KEY}" = "CHANGE_ME_TO_A_SECURE_RANDOM_STRING" ] || [ -z "${EXISTING_API_KEY}" ]; then
    echo "ERROR: API_KEY is not set or still using placeholder value!"
    echo "Run ./setup.sh first to initialize the application."
    exit 1
fi

# Load HTTP_PORT from .env for display
set -a
source .env
set +a

# Start the application in detached mode
echo "Starting EcoGallery services..."
docker compose up -d --pull always
echo ""

# Show status
docker compose ps
echo ""
echo "======================================"
echo "  EcoGallery is running!"
echo "======================================"
echo ""
if [ -z "${HTTP_PORT}" ] || [ "${HTTP_PORT}" = "80" ]; then
    echo "Access the application at: http://localhost"
else
    echo "Access the application at: http://localhost:${HTTP_PORT}"
fi
echo ""
echo "Useful commands:"
echo "  docker compose logs -f          # View logs"
echo "  docker compose down             # Stop ecogallery"
echo "  docker compose ps               # Check status"
echo "======================================"